[package]
name = "sql-models"
version = "0.1.0"
authors = ["Austin Hyde <austin109@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]