[package]
name = "query-cli"
version = "0.1.0"
authors = ["Austin Hyde <austin109@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.9"
sql-parser = {path="../sql-parser"}
sql-models = {path="../sql-models"}
csv = "1.1.3"
